#!/usr/bin/env bun

import { Command } from 'commander';
import fs from 'fs';
import path from 'path';

const program = new Command();
program.nameFromFilename(__filename)
program.showHelpAfterError()

program
    .command('migration <name>')
    .description('Create a new migration file')
    .action((target, options) => {
        if (!target) return;

        function formatDate(date) {
            const pad = (n: number) => String(n).padStart(2, '0');
            return (
                date.getFullYear().toString() +
                pad(date.getMonth() + 1) +
                pad(date.getDate()) +
                pad(date.getHours()) +
                pad(date.getMinutes()) +
                pad(date.getSeconds())
            );
        }

        fs.mkdirSync(path.join(__dirname, 'migrations'), { recursive: true });
        fs.writeFileSync(path.join(__dirname, 'migrations', `${formatDate(new Date())}_${target}.sql`), '');
    });

program.parse();

